[package]
name = "agentsmith"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "agentsmith-common",
    "agentsmith-agent",
    "agentsmith-eval",
    "agentsmith-prompt",
    "agentsmith-runtime",
    "agentsmith-orchestrator",
    "agentsmith-worker",
    "agentsmith-web"
]

[dependencies]


#[build-dependencies]
#cargo-workspaces = "0.3.6"