[package]
name = "agentsmith-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
agentsmith-common = { path = "../agentsmith-common"}
agentsmith-agent = { path = "../agentsmith-agent"}

pyo3 = { version = "0.22.3", features = ["extension-module"] }

tokio = { version = "1.40", features = ["full"] }
tokio-tungstenite = "0.24"
serde = "1.0"
serde_json = "1.0"

[build-dependencies]
tonic-build = "0.12"
prost-build = "0.13"


[dev-dependencies]
anyhow = "1"
httpc-test = "0.1"
testcontainers = "0.23"