[package]
name = "agentsmith-common"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12.1"
serde = "1.0"
serde_json = "1.0"
strum_macros = "0.26.2"
redis = {  version = "0.27", features = ["tokio-comp", "json", "connection-manager", "streams"] }
r2d2 = "0.8"
r2d2_redis = "0.14"

chrono = "0.4"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.24"
tower = { version = "0.5", features = ["util"] }
tower-http = { version = "0.6", features = ["fs", "trace", "cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
log = "0.4"
jsonwebtoken = "9"
reqwest = { version = "0.12", features = ["json"] }

axum = { version = "0.7", features = ["ws", "tracing", "macros"] }

async-trait = "0.1.80"
sqlx = { version = "0.8", features = ["runtime-async-std-native-tls", "mysql", "chrono", "uuid"] }