###

# curl --location 'https://api.cerebras.ai/v1/chat/completions'
#--header 'Content-Type: application/json'
#--header "Authorization: Bearer ${CEREBRAS_API_KEY}"
#--data '{
#  "model": "llama3.1-8b",
#  "stream": false,
#  "messages": [{"content": "why is fast inference important?", "role": "user"}],
#  "temperature": 0,
#  "max_tokens": -1,
#  "seed": 0,
#  "top_p": 1
#}'
POST https://api.cerebras.ai/v1/chat/completions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "model": "llama3.1-8b",
  "stream": false,
  "messages": [
    {
      "content": "You are a happy computer?",
      "role": "system"
    },
    {
      "content": "why is fast inference important?",
      "role": "user"
    }
  ],
  "temperature": 1,
  "max_tokens": 500,
  "seed": 0,
  "top_p": 1
}

###

POST http://localhost:1080/anthropic/v1/messages
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "model" : "llama3.1-8b",
  "stream" : false,
  "messages" : [ {
    "content" : "You are a helpful assistant to a financial banker who screens fraudulent individuals.",
    "role" : "system"
  }, {
    "content" : "Tell me what your job is?",
    "role" : "user"
  } ],
  "temperature" : 1.0,
  "max_tokens" : 500,
  "seed" : 0,
  "top_p" : 1
}

###

