POST https://api.anthropic.com/v1/messages
x-api-key: {{anthropic_token}}
anthropic-version: 2023-06-01
Content-Type: application/json

{
  "model": "claude-3-5-sonnet-20240620",
  "max_tokens": 1024,
  "tools": [
    {
      "name": "get_weather",
      "description": "Get the current weather in a given location",
      "input_schema": {
        "type": "object",
        "properties": {
          "location": {
            "type": "string",
            "description": "The city and state, e.g. San Francisco, CA"
          }
        },
        "required": ["location"]
      }
    },
    {
      "name": "get_cloud_cover",
      "description": "Get the current cloud cover for a location.",
      "input_schema": {
        "type": "object",
        "properties": {
          "location": {
            "type": "string",
            "description": "The city and state, e.g. San Francisco, CA"
          }
        },
        "required": ["location"]
      }
    }
  ],
  "messages": [
    {
      "role": "user",
      "content": "What is the weather and cloud cover like in San Francisco?"
    }
  ]
}

###
POST https://api.anthropic.com/v1/messages
x-api-key: {{anthropic_token}}
anthropic-version: 2023-06-01
Content-Type: application/json

{
  "model": "claude-3-5-sonnet-20240620",
  "system": "You are a helpful assistant to a financial banker who screens fraudulent individuals.",
  "messages": [
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "You are a helpful assistant to a financial banker who screens fraudulent individuals."
        }
      ]
    }
  ],
  "max_tokens": 500,
  "temperature": 1.0,
  "top_p": 1.0,
  "stream": false
}

###

POST http://localhost:1080/anthropic/v1/messages
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "model" : "llama3.1-8b",
  "stream" : false,
  "messages" : [ {
    "content" : "You are a helpful assistant to a financial banker who screens fraudulent individuals.",
    "role" : "system"
  }, {
    "content" : "Tell me what your job is?",
    "role" : "user"
  } ],
  "temperature" : 1.0,
  "max_tokens" : 500,
  "seed" : 0,
  "top_p" : 1
}

###

