name: Build AgentSmith
run-name: ${{ github.actor }} testing the build succeeds.
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --workspace --verbose
#      - name: Run tests
#        run: cargo test --verbose
